# Temporarily disabled due to error in action-eslint
# Ref. https://github.com/reviewdog/action-eslint/issues/56
# name: reviewdog
# on: [pull_request]
# jobs:
#   eslint:
#     name: runner / eslint
#     runs-on: ubuntu-latest
#     if: ${{ !contains(github.head_ref, 'dependabot/') }}
#     steps:
#       - uses: actions/checkout@v2
#       - name: eslint
#         uses: reviewdog/action-eslint@v1
#         with:
          # github_token: ${{ secrets.github_token }}
